# Docker-compose that runs the production.
version: "3.4"

networks:
  backend:
  frontend:

services:
  picspy-api:
    image: registry.qtmsheep.com/vagahbond/picspy/api:latest
    ports:
      - "${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}"
    depends_on: 
      - picspy-mongo
    networks: 
      - backend
    env_file: 
      - .env

  picspy-mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    ports: 
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks: 
      - backend
    env_file: 
      - .env

