export default [
  {
    _id: 'challenge1',
    name: 'first',
    instructions: 'test instructions 1',
    imageUrl: '../images/coding.jpg',
    done: false,
  },
  {
    _id: 'challenge2',
    name: 'second',
    instructions: 'test instructions 2',
    imageUrl: '../images/contact-petit-3.png',
    done: true,
  },
  {
    _id: 'challenge2',
    name: 'second',
    instructions: 'test instructions 2',
    imageUrl: '../images/contact-petit-3.png',
    done: true,
  },
  {
    _id: 'challenge2',
    name: 'second',
    instructions: 'test instructions 2',
    imageUrl: '../images/contact-petit-3.png',
    done: true,
  },
  {
    _id: 'challenge2',
    name: 'second',
    instructions: 'test instructions 2',
    imageUrl: '../images/contact-petit-3.png',
    done: true,
  },
  {
    _id: 'challenge2',
    name: 'second',
    instructions: 'test instructions 2',
    imageUrl: '../images/contact-petit-3.png',
    done: true,
  },
  {
    _id: 'challenge2',
    name: 'second',
    instructions: 'test instructions 2',
    imageUrl: '../images/contact-petit-3.png',
    done: true,
  },
  {
    _id: 'challenge2',
    name: 'second',
    instructions: 'test instructions 2',
    imageUrl: '../images/contact-petit-3.png',
    done: true,
  },
  {
    _id: 'challenge2',
    name: 'second',
    instructions: 'test instructions 2',
    imageUrl: '../images/contact-petit-3.png',
    done: true,
  },
  {
    _id: 'challenge2',
    name: 'second',
    instructions: 'test instructions 2',
    imageUrl: '../images/contact-petit-3.png',
    done: true,
  },
  {
    _id: 'challenge2',
    name: 'second',
    instructions: 'test instructions 2',
    imageUrl: '../images/contact-petit-3.png',
    done: true,
  },
  {
    _id: 'challenge2',
    name: 'second',
    instructions: 'test instructions 2',
    imageUrl: '../images/contact-petit-3.png',
    done: true,
  },{
    _id: 'challenge2',
    name: 'second',
    instructions: 'test instructions 2',
    imageUrl: '../images/contact-petit-3.png',
    done: true,
  },

];
